name: Publish vue-semi-design to npm

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pull repo
        uses: actions/checkout@v2
      - name: node version
        uses: actions/setup-node@v3
        with:
          node-version: 22.18.0
          registry-url: https://registry.npmjs.org
      - name: npm cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm i -g pnpm && pnpm i
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: publish
        run: cd packages/vue-semi-design && npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
